---

- name: Pull latest changes from GitHub
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"
    update: yes

- name: Set Node version
  command: nvm use
  args:
    chdir: '{{ project_path }}'

- name: Build webpack bundles
  command: yarn build.prod
  args:
    chdir: '{{ project_path }}'
