---

- name: Provision JTT Servers
  hosts: justthetip
  become: true
  become_method: sudo
  gather_facts: no
  pre_tasks:
  - name: Install Python
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal && sudo apt install -y python-apt)
    register: output
    changed_when: output.stdout != ""
  roles:
    - provision

# Use second play here to avoid unnecessary privilege escalation
- name: Clone Repo from GitHub
  hosts: justthetip
  gather_facts: yes
  roles:
    - clone
